# Connection string to use for XonStatDB PostgreSQL database
ConnStr = "user=xonstat host=localhost dbname=xonstatdb sslmode=disable"

# D0_BLIND_ID verification
VerifyRequests = true
D0BlindIDKeyGen = "/usr/local/bin/crypto-keygen-standalone"
D0BlindIDPubKey = "~/key_0.d0pk"

# How many (human) players are required to store matches
MinimumRequiredPlayers = 2

# Request logging
RequestsLogAll = false
RequestsLogFile = "xonstat-requests.log"
RequestsLogMaxSize = 100
RequestsMaxBackups = 5
RequestsMaxAge = 14

# Time limits controlling how much history is shown on various pages
SummaryStatsDays = 30
RecentGamesDays = 30